@startuml
'https://plantuml.com/sequence-diagram

autonumber



group 额度恢复
autonumber 1.0
    alt 非kredito渠道
        activate 业务层
        业务层 ->业务层:查询到支付单状态为支付成功

        activate transaction模块
        业务层 -> transaction模块 : 获取具体支付方式
        transaction模块->账户模块 : 调用处理还款业务逻辑接口
        账户模块 -> 账户模块 : 查询对应渠道的具体账户
        账户模块 -> 账户模块 : 业务单幂等性校验
        账户模块 -> 账户模块 : 校验账户状态
        账户模块 -> 账户模块 : 保存账户变更记录与详情
        账户模块 -> 账户模块 : 恢复账户额度
        账户模块 -> transaction模块 :
        transaction模块 -> 业务层 :
        deactivate transaction模块

        deactivate 业务层

    else kredito渠道
        note right of 业务层: kredito渠道额度使用实时计算方式获得，随着账单结清自动恢复额度
    end
end


@enduml