@startuml
'https://plantuml.com/sequence-diagram


autonumber

group 业务暂时不调
autonumber 1.0
业务侧 -> rc_tunnel:用户提交前触发调用风控
rc_tunnel -> 风控编排层:提交风控引擎
alt 灰度判断:风控中台陪跑 + 旧规则引擎
    autonumber 1.1
    风控编排层 -> 风控中台:
    风控中台 -> 风控编排层:
    风控编排层 -> 旧规则引擎:
    旧规则引擎 -> 风控编排层:
else 走旧规则引擎
    autonumber 1.1
    风控编排层 -> 旧规则引擎:
    旧规则引擎 -> 风控编排层:
else 走风控中台
    autonumber 1.1
    风控编排层 -> 风控中台:
    风控中台 -> 风控编排层:
end
风控编排层 -> rc_tunnel: 返回结果
rc_tunnel -> 业务侧: 返回结果
end

autonumber 2.0
业务侧 -> rc_tunnel: 交易提交审核接口
rc_tunnel -> rc_tunnel : 是否灰度逻辑判断
rc_tunnel -> 风控编排层: 提交一审/规则前校验
alt 灰度用户
    autonumber 2.1
    风控编排层 -> 风控中台:单提交
    风控中台 -> 风控编排层:结果返回
else 非灰度用户
    autonumber 2.1
    group 陪跑
        风控编排层 -> 旧规则引擎:走旧流程
        旧规则引擎 -> 风控编排层:结果返回
    end
    风控编排层 -> 风控中台:提交中台
    风控中台 -> 风控编排层:结果返回
end
风控编排层 -> rc_tunnel:返回鉴权信息



autonumber 3.0
rc_tunnel -> 风控编排层: 提交交易鉴权
alt 灰度用户
    autonumber 3.1
    风控编排层 -> 风控中台:单提交
    风控中台 -> 风控编排层:结果返回
else 非灰度用户
    autonumber 3.1
    group 陪跑
        风控编排层 -> 旧规则引擎:走旧流程
        旧规则引擎 -> 风控编排层:结果返回
    end
    风控编排层 -> 风控中台:提交中台
    风控中台 -> 风控编排层:结果返回
end
风控编排层 -> rc_tunnel:返回鉴权信息

autonumber 4.0
rc_tunnel -> 风控编排层: 提交二审
alt 灰度用户
    autonumber 4.1
    风控编排层 -> 风控中台:单提交
    风控中台 -> 风控编排层:结果返回
else 非灰度用户
    autonumber 4.1
    group 陪跑
        风控编排层 -> 旧规则引擎:走旧流程
        旧规则引擎 -> 风控编排层:结果返回
    end
    风控编排层 -> 风控中台:提交中台
    风控中台 -> 风控编排层:结果返回
end
风控编排层 -> rc_tunnel:返回结果信息
rc_tunnel -> 业务侧: 返回审核结果(审核中/通过/拒绝)


autonumber
业务侧 -> rc_tunnel: 查询交易单审核结果
rc_tunnel -> 风控编排层:查询风控交易信息
风控编排层 -> 风控编排层:转化交易状态，判断状态
alt 拒绝/关单
    风控编排层 -> 风控编排层:判断是否是人工审核
    alt 是
        风控编排层 -> risk_approval:查询人工审核结果(/manual/query/selectByUniqueKey)
        risk_approval -> 风控编排层:返回人工审核结果
        风控编排层 -> 风控编排层:设置人工审核拒绝码
    else 不是
        风控编排层 -> autoaudit_water:查询风控审核流水(/autoaudit/water/queryTradeRcByNode)
        autoaudit_water -> 风控编排层:返回风控审核流水
        风控编排层 -> 风控编排层:设置自动审核拒绝码
    end
    风控编排层 -> rc_tunnel:返回交易单审核结果
    rc_tunnel -> 业务侧:返回交易单审核结果
else 通过/拒绝/审核中
    风控编排层 -> rc_tunnel:返回交易单审核结果
    rc_tunnel -> 业务侧:返回交易单审核结果
end
@enduml